### ISSUE TITLE
Question about running your codes

### ISSUE THREAD

**Issue by mamengyiyi** [FangchenLiu/MaskDP_public#1]
Hi, thanks for sharing your codes. I'm wondering how to run MaskDP from scratch for offline RL as plotted in Figure 8 of your paper https://arxiv.org/pdf/2211.12740.pdf. Could you please provide corresponding shell script or command?

**Comment by FangchenLiu** [comment]
check https://github.com/FangchenLiu/MaskDP_public/blob/67f36897829f32106f13e54ddda5cf7076f7bda1/agent/mdp_multitask.py#L199-L201 where `path` is not provided, the model weights will be randomly initialized.
